### PR TITLE
Formatting change

### PR DESCRIPTION
**Pull request by jeff-matthews**
Test

whatsnew
[magento/devdocs-mbi](https://github.com/magento/devdocs-mbi) test.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@magento import pr to magento-devdocs/devdocs-mbi

**Comment by magento-engcom-team** [comment]
@jeff-matthews the pull request successfully imported.

**Comment by dshevtsov** [comment]
@magento import pr to magento-devdocs/devdocs-mbi

**Comment by magento-engcom-team** [comment]
@dshevtsov the pull request successfully imported.

**Comment by dshevtsov** [comment]
@magento import code to magento-devdocs/devdocs-mbi

**Comment by dshevtsov** [comment]
@magento import code to magento-devdocs/devdocs-mbi

**Comment by magento-engcom-team** [comment]
@dshevtsov the branch with code successfully imported into`magento-devdocs/devdocs-mbi` repository. Branch name: `imported-magento-devdocs-mbi-16`.

**Comment by magento-engcom-team** [comment]
@dshevtsov the branch with code successfully imported into`magento-devdocs/devdocs-mbi` repository. Branch name: `imported-magento-devdocs-mbi-16`.

**Comment by dshevtsov** [comment]
@magento import code to magento-devdocs/devdocs-mbi

**Comment by magento-engcom-team** [comment]
@dshevtsov the branch with code successfully imported into`magento-devdocs/devdocs-mbi` repository. Branch name: `imported-magento-devdocs-mbi-16`.

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/devdocs-mbi

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs-mbi` repository. Branch name: `imported-magento-devdocs-mbi-16`.

**Comment by dshevtsov** [comment]
@jeff-matthews, please update your branch with latest `master`.

**Comment by jeff-matthews** [comment]
@dshevtsov, why? This isn't a real PR.

**Comment by dshevtsov** [comment]
@jeff-matthews, I need it for testing.

**Comment by jeff-matthews** [comment]
@dshevtsov, done.

**Comment by dshevtsov** [comment]
@magento import code to magento-devdocs/devdocs-mbi

**Comment by magento-engcom-team** [comment]
@dshevtsov the branch with code successfully imported into`magento-devdocs/devdocs-mbi` repository. Branch name: `imported-magento-devdocs-mbi-16`.

**Review by dshevtsov — APPROVED** [review]

**Pull request merged**
