### PR TITLE
Test format change

### PR DESCRIPTION
**Pull request by jeff-matthews**

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@magento import pull request to magento-devdocs/devdocs-mbi

**Comment by magento-engcom-team** [comment]
@jeff-matthews, an error occurred during the Pull Request import.

**Comment by jeff-matthews** [comment]
@magento import pr to magento-devdocs/devdocs-mbi

**Comment by magento-engcom-team** [comment]
@jeff-matthews, an error occurred during the Pull Request import.

**Comment by sidolov** [comment]
@magento import pr to magento-devdocs/devdocs-mbi

**Comment by magento-engcom-team** [comment]
@sidolov, an error occurred during the Pull Request import.

**Comment by jeff-matthews** [comment]
@magento import pr to magento-devdocs/devdocs-mbi

**Comment by magento-engcom-team** [comment]
@jeff-matthews, an error occurred during the Pull Request import.

**Comment by jeff-matthews** [comment]
@magento import pr to magento-devdocs/devdocs-mbi

**Comment by magento-engcom-team** [comment]
@jeff-matthews, an error occurred during the Pull Request import.

**Comment by sidolov** [comment]
@magento import pr to magento-devdocs/devdocs-mbi

**Comment by magento-engcom-team** [comment]
@sidolov, an error occurred during the Pull Request import.

**Comment by sidolov** [comment]
@magento import pr to magento-devdocs/devdocs-mbi

**Comment by magento-engcom-team** [comment]
@sidolov the pull request successfully imported.

**Pull request merged**
